//North America Only
SELECT 
    EXTRACTION_DATE,
    CSAV_ACCOUNT_NAME as CAV_ACCOUNT_NAME,
    --SUM(CASE WHEN INTERSIGHT_CONSUMPTION = 'pApp' THEN QUANTITY ELSE 0 END) AS PVA_LICENSES,
    SUM(CASE WHEN (INTERSIGHT_CONSUMPTION = 'vApp' 
        or INTERSIGHT_CONSUMPTION = 'SaaS' ) THEN QUANTITY ELSE 0 END) AS SAAS_LICENSES,
      SUM(CASE WHEN LICENSE_TIER ilike '%Essential%' THEN QUANTITY ELSE 0 END) as ENTITLED_ESSENTIALS,
    SUM(CASE WHEN LICENSE_TIER ilike '%Advantage%' THEN QUANTITY ELSE 0 END) as ENTITLED_ADVANTAGE,
    SUM(CASE WHEN LICENSE_TIER ilike '%Premier%'  THEN QUANTITY ELSE 0 END) as ENTITLED_PREMIER,
    SUM(CASE WHEN LICENSE_TIER ilike '%Essential%' or LICENSE_TIER ilike '%Advantage%' or LICENSE_TIER ilike '%Premier%' THEN QUANTITY ELSE 0 END ) as ENTITLED_PAID
FROM engit_db.engit_isdatamart_br.cafe_subscription_f 
where INTERSIGHT_PRODUCT = 'Intersight Core'
    and LICENSE_TIER in ('Advantage', 'Essentials', 'Premier')
    and extraction_date = current_date and INTERSIGHT_CONSUMPTION != 'pApp'
GROUP BY EXTRACTION_DATE, CAV_ACCOUNT_NAME 
order by CAV_ACCOUNT_NAME asc